project:
  title: "ManyBabies 4"
  type: datapage

website:
  navbar:
    logo: images/logo.png

format:
  datapage-html:
    theme: theme.scss

execute: 
  echo: false
  message: false
  warning: false
  error: false

redivis:
  user: datapages
  dataset: many_babies_4
  table: clean_data
  # workflow: many_babies_4_analysis
  # table: primary_data
